rvm:
  - 1.9.2
  - ruby-head
  - rbx
  - rbx-2.0
  - jruby
branches:
  only:
    - master
    - stable
before_script:
  - "mysql -e 'create database cartoque_test;'"
  - "cp config/database.yml.travis config/database.yml"
script: "bundle exec rake db:migrate db:seed test"
