rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
    - stable
env: RAILS_ENV=test
before_script:
  - "mysql -e 'create database cartoque_test;'"
  - "cp config/database.yml.travis config/database.yml"
  - "bundle exec rake db:schema:load db:seed"
script: "bundle exec rspec spec"
