development:
  sessions:
    default:
      database: cartoque
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: cartoque_test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  sessions:
    default:
      database: <%= ENV['MONGOID_DATABASE'] || 'cartoque' %>
      hosts:
        - <%= ENV['MONGOID_HOST'] || 'localhost' %>:<%= ENV['MONGOID_PORT'] || '27017' %>
      # - slave.local:27017
      #username: <%= ENV['MONGOID_USERNAME'] %>
      #password: <%= ENV['MONGOID_PASSWORD'] %>
      logger: false
