development:
  host: localhost
  database: cartoque

test:
  host: localhost
  database: cartoque_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] || 'localhost' %>
  port: <%= ENV['MONGOID_PORT'] || '27017' %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] || 'cartoque' %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
