settings: &settings
#  google_analytics_key: &google
#    alt: Google analytics key
#    value: 'UA-xxxxxx-x'
#    editable: true
#    deletable: false
#    validations:
#      presence: true
#  search_algorithm:
#    alt: Default search engine
#    value: 'ferret'
#    editable: true
#    validations:
#      inclusion: [ 'ferret' , 'sphinx' ]
#  white_list:
#    alt: 'White-listed words'
#    value: 'herp, derp'
  site_announcement_message:
    editable: true
  site_announcement_type:
    editable: true
  cas_server:
    value: 'https://authentification-cerbere.application.i2/cas/'
    editable: true
  redmine_url: &redmine
    editable: true
  dns_domains:
    value: "ac.cs\nac.centre-serveur.i2\nac.melanie2.i2\ncsac.melanie2.i2\nappli.i2\napplication.ac.centre-serveur.i2\napp.ac.cs\nsgbd.ac.cs\napp.ac.cs\ninfocentre.i2"
    editable: true
  allow_internal_authentication:
    value: "yes"
    editable: true

development:
  <<: *settings  
#  google_analytics_key:
#    <<: *google
#    alt: Development Google analytics key
#    value: 'UA-xxxxxx-1'
  cas_server:
    value: 'http://localhost:9292'
  redmine_url:
    <<: *redmine
    value: 'http://localhost:3001/'

test:
  <<: *settings
  redmine_url:
    <<: *redmine
    value: 'http://redmine.test.host'

production:
  <<: *settings
  redmine_url:
    <<: *redmine
    value: 'http://redmine.app.ac.centre-serveur.i2/'
